GET http://localhost:4000/users/delete
###
POST http://localhost:4000/signup

{
    'email': "",
    'name': ""
}
###
POST http://localhost:4000/
###
GET http://localhost:5000/user/ajlkdfk

###
POST http://localhost:4000/user/delete
Content-Type: application/json

{
    "password": "mission@1234"
}